### ISSUE TITLE
How to send a document using this repo

### ISSUE THREAD

**Issue by hammadyounas2008** [fbsamples/messenger-platform-samples#155] opened 2021-10-08 15:49 UTC
I have a document file I want to send through this repo how can I processed it?

**Comment by Ghaethliii** [comment] 2021-12-16 19:01
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

**Comment by Ghaethliii** [comment] 2021-12-16 19:01
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

**Comment by Ghaethliii** [comment] 2021-12-16 19:01
Duplicate of #

**Comment by Barbog** [comment] 2022-01-04 16:04
This repo does not demonstrate the sending of generic files. However, you can find some examples of sending image attachments in 
* `messenger-platform-samples/node/app.js` — from line 411

Check the docs in https://developers.facebook.com/docs/messenger-platform/send-messages#sending_attachments for more examples.

**Closed by Barbog** 2022-01-04 16:04 UTC
